# Generated by Django 3.2.7 on 2021-10-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("miniblogapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
